### ISSUE TITLE
Run: TypeError: Cannot write private member to an object whose class did not declare it

### ISSUE THREAD

**Issue by olivergondza** [AutoModality/action-xunit-viewer#17]
Running the action fails with:

```
TypeError: Cannot write private member to an object whose class did not declare it
    at O (/usr/local/lib/node_modules/xunit-viewer/node_modules/yargs/build/index.cjs:1:3385)
    at showHelp (/usr/local/lib/node_modules/xunit-viewer/node_modules/yargs/build/index.cjs:1:42255)
    at module.exports (/usr/local/lib/node_modules/xunit-viewer/xunit-viewer.js:19:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/xunit-viewer/bin/xunit-viewer:6:1)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.13.0
```

Tested with `ubuntu-latest` and `18.04`, `action-xunit-viewer@v1.0.1` and `action-xunit-viewer@v1`.

**Comment by tking16** [comment]
Getting this issue too
